spring:
  application:
    name: coding-shuttle-learning

  datasource:
    url: jdbc:mysql://localhost:3306/spring_data_homework?useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update # Existing table will be dropped and on each restart new table will be created.
      format_sql: true
    #      dialect: org.hibernate.dialect.MySQL5Dialect -> optional
    show-sql: true # for debugging purpose

kind: Application

# Logger configuration
logging:
  file:
    path: logs
    name: Application.logs